#####
# Note: all insert statements must be on a single line.  If the insert statement
# breaks over two lines, the CR/LF will cause an error on execution of the statement.
#####


#####
# inserts for STATE table
#####

INSERT INTO STATE (NAME, CODE) VALUES ('Alabama', 'AL');

INSERT INTO STATE (NAME, CODE) VALUES ('Alaska', 'AK');

INSERT INTO STATE (NAME, CODE) VALUES ('Arizona', 'AZ');

INSERT INTO STATE (NAME, CODE) VALUES ('Arkansas', 'AR');

INSERT INTO STATE (NAME, CODE) VALUES ('California', 'CA');

INSERT INTO STATE (NAME, CODE) VALUES ('Colorado', 'CO');

INSERT INTO STATE (NAME, CODE) VALUES ('Connecticut', 'CT');

INSERT INTO STATE (NAME, CODE) VALUES ('Delaware', 'DE');

INSERT INTO STATE (NAME, CODE) VALUES ('District of Columbia', 'DC');

INSERT INTO STATE (NAME, CODE) VALUES ('Florida', 'FL');

INSERT INTO STATE (NAME, CODE) VALUES ('Georgia', 'GA');

INSERT INTO STATE (NAME, CODE) VALUES ('Hawaii', 'HI');

INSERT INTO STATE (NAME, CODE) VALUES ('Idaho', 'ID');

INSERT INTO STATE (NAME, CODE) VALUES ('Illinois', 'IL');

INSERT INTO STATE (NAME, CODE) VALUES ('Indiana', 'IN');

INSERT INTO STATE (NAME, CODE) VALUES ('Iowa', 'IA');

INSERT INTO STATE (NAME, CODE) VALUES ('Kansas', 'KS');

INSERT INTO STATE (NAME, CODE) VALUES ('Kentucky', 'KY');

INSERT INTO STATE (NAME, CODE) VALUES ('Louisiana', 'LA');

INSERT INTO STATE (NAME, CODE) VALUES ('Maine', 'ME');

INSERT INTO STATE (NAME, CODE) VALUES ('Maryland', 'MD');

INSERT INTO STATE (NAME, CODE) VALUES ('Massachusetts', 'MA');

INSERT INTO STATE (NAME, CODE) VALUES ('Michigan', 'MI');

INSERT INTO STATE (NAME, CODE) VALUES ('Minnesota', 'MN');

INSERT INTO STATE (NAME, CODE) VALUES ('Mississippi', 'MS');

INSERT INTO STATE (NAME, CODE) VALUES ('Missouri', 'MO');

INSERT INTO STATE (NAME, CODE) VALUES ('Montana', 'MT');

INSERT INTO STATE (NAME, CODE) VALUES ('Nebraska', 'NE');

INSERT INTO STATE (NAME, CODE) VALUES ('Nevada', 'NV');

INSERT INTO STATE (NAME, CODE) VALUES ('New Hampshire', 'NH');

INSERT INTO STATE (NAME, CODE) VALUES ('New Jersey', 'NJ');

INSERT INTO STATE (NAME, CODE) VALUES ('New Mexico', 'NM');

INSERT INTO STATE (NAME, CODE) VALUES ('New York', 'NY');

INSERT INTO STATE (NAME, CODE) VALUES ('North Carolina', 'NC');

INSERT INTO STATE (NAME, CODE) VALUES ('North Dakota', 'ND');

INSERT INTO STATE (NAME, CODE) VALUES ('Ohio', 'OH');

INSERT INTO STATE (NAME, CODE) VALUES ('Oklahoma', 'OK');

INSERT INTO STATE (NAME, CODE) VALUES ('Oregon', 'OR');

INSERT INTO STATE (NAME, CODE) VALUES ('Pennsylvania', 'PA');

INSERT INTO STATE (NAME, CODE) VALUES ('Rhode Island', 'RI');

INSERT INTO STATE (NAME, CODE) VALUES ('South Carolina', 'SC');

INSERT INTO STATE (NAME, CODE) VALUES ('South Dakota', 'SD');

INSERT INTO STATE (NAME, CODE) VALUES ('Tennessee', 'TN');

INSERT INTO STATE (NAME, CODE) VALUES ('Texas', 'TX');

INSERT INTO STATE (NAME, CODE) VALUES ('Utah', 'UT');

INSERT INTO STATE (NAME, CODE) VALUES ('Vermont', 'VT');

INSERT INTO STATE (NAME, CODE) VALUES ('Virginia', 'VA');

INSERT INTO STATE (NAME, CODE) VALUES ('Washington', 'WA');

INSERT INTO STATE (NAME, CODE) VALUES ('West Virginia', 'WV');

INSERT INTO STATE (NAME, CODE) VALUES ('Wisconsin', 'WI');

INSERT INTO STATE (NAME, CODE) VALUES ('Wyoming', 'WY');

#####
# inserts for USER_TYPE table
#####

INSERT INTO USER_TYPE (DESCRIPTION) VALUES ('ADMINISTRATOR');

INSERT INTO USER_TYPE (DESCRIPTION) VALUES ('CUSTOMER');

#####
# inserts for EMAIL_TYPE table
#####

INSERT INTO EMAIL_TYPE (DESCRIPTION) VALUES ('BUSINESS');

INSERT INTO EMAIL_TYPE (DESCRIPTION) VALUES ('PERSONAL');

INSERT INTO EMAIL_TYPE (DESCRIPTION) VALUES ('OTHER');


#####
# inserts for PHONE_TYPE table
#####

INSERT INTO PHONE_TYPE (DESCRIPTION) VALUES ('BUSINESS');

INSERT INTO PHONE_TYPE (DESCRIPTION) VALUES ('PERSONAL');

INSERT INTO PHONE_TYPE (DESCRIPTION) VALUES ('FAX');

INSERT INTO PHONE_TYPE (DESCRIPTION) VALUES ('OTHER');

#####
# inserts for PARKING_LOT table
#####
INSERT INTO PHONE (ACCEPTS_TEXT, PHONE_NUMBER, PHONE_TYPE_ID) VALUES (FALSE, '8015544891', 1);

INSERT INTO EMAIL (EMAIL_ADDRESS, EMAIL_TYPE_ID) VALUES ('parkandjet@hotmail.com', 1);

INSERT INTO PARKING_LOT (CITY, NAME, STATE_ID, STREET, ZIP_CODE, EMAIL_ID, PRIMARY_PHONE_ID) VALUES ('Salt Lake City', 'Park and Jet', 45, '2200 West North Temple', '84116', 1, 1);

#####
# inserts for VALUE_TYPE table
#####

INSERT INTO AMOUNT_TYPE(DESCRIPTION) VALUES ('TAX_RATE');

INSERT INTO AMOUNT_TYPE(DESCRIPTION) VALUES ('DAILY_RATE');

#####
# inserts for VALUE table
#####

INSERT INTO AMOUNT(AMOUNT_TYPE_ID, PARKING_LOT_ID, AMOUNT) VALUES (1, 1, 0.065);

INSERT INTO AMOUNT(AMOUNT_TYPE_ID, PARKING_LOT_ID, AMOUNT) VALUES (2, 1, 6.0);

#####
# TEST inserts for USER table (Includes PHONE and EMAIL)
#####
INSERT INTO PHONE (ACCEPTS_TEXT, PHONE_NUMBER, PHONE_TYPE_ID) VALUES (TRUE, '8015554890', 2);

INSERT INTO EMAIL (EMAIL_ADDRESS, EMAIL_TYPE_ID) VALUES ('myaddress@hotmail.com', 2);

# password_md5 decode = 'gateshead'
INSERT INTO USER (CITY, DATE_CREATED, FIRST_NAME, LAST_NAME, PASSWORD_MD5, STREET, USER_NAME, ZIP_CODE, PRIMARY_EMAIL_ID, PRIMARY_PHONE_ID, STATE_ID, USER_TYPE_ID) VALUES ('Farmington', CURDATE(), 'Brian', 'Johnson','df2f12d1f3a4b3c467579e240107e83f', '1220 South 300 East', 'bjohnson', '84417', 2, 2, 1, 2);

# This is an administrative user
INSERT INTO PHONE (ACCEPTS_TEXT, PHONE_NUMBER, PHONE_TYPE_ID) VALUES (FALSE, '8045557760', 2);

INSERT INTO EMAIL (EMAIL_ADDRESS, EMAIL_TYPE_ID) VALUES ('adminaddress@hotmail.com', 2);

# password_md5 decode = 'parkingAdmin'
INSERT INTO USER (CITY, COMPANY_NAME, DATE_CREATED, FIRST_NAME, LAST_NAME, PASSWORD_MD5, STREET, USER_NAME, ZIP_CODE, PRIMARY_EMAIL_ID, PRIMARY_PHONE_ID, STATE_ID, USER_TYPE_ID) VALUES ('Centerville', 'Rand Enterprises', CURDATE(), 'John', 'Gault','5dfda6370209774e916ab82db056e0a0', '590 West Atlas Street', 'admin', '89481', 3, 3, 5, 1);

#####
# TEST inserts for VEHICLE table
#####
INSERT INTO VEHICLE (COLOR, MAKE, MODEL, PLATE_NUMBER, USER_ID) VALUES ('RED', 'PORSCHE', '911', '78HUT5', 1);

INSERT INTO VEHICLE (COLOR, MAKE, MODEL, PLATE_NUMBER, USER_ID) VALUES ('BLACK', 'NISSAN', 'TITAN', '667MPQ', 1);

INSERT INTO VEHICLE (COLOR, MAKE, MODEL, PLATE_NUMBER, USER_ID) VALUES ('WHITE', 'HONDA', 'ACCORD', '547NPA', 1);

INSERT INTO VEHICLE (COLOR, MAKE, MODEL, PLATE_NUMBER, USER_ID) VALUES ('BLACK', 'HYUNDAI', 'ELANTRA', '99MFG5', 1);

INSERT INTO VEHICLE (COLOR, MAKE, MODEL, PLATE_NUMBER, USER_ID) VALUES ('WHITE', 'FORD', 'MUSTANG', '889MPH', 2);

INSERT INTO VEHICLE (COLOR, MAKE, MODEL, PLATE_NUMBER, USER_ID) VALUES ('ORANGE', 'DODGE', 'PICKUP', '90NYU7', 2);

#####
# inserts for PARKING_SLOT table
#####
# Section A
INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('A1', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('A2', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('A3', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('A4', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('A5', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('A6', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('A7', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('A8', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('A9', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('A10', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('A11', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('A12', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('A13', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('A14', 1);

# Section B
INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B1', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B2', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B3', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B4', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B5', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B6', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B7', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B8', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B9', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B10', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B11', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B12', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B13', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B14', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B15', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B16', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B17', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B18', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B19', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B20', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B21', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B22', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B23', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B24', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B25', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B26', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B27', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B28', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B29', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B30', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B31', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B32', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B33', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B34', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B35', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('B36', 1);

# Section C
INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C1', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C2', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C3', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C4', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C5', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C6', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C7', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C8', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C9', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C10', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C11', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C12', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C13', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C14', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C15', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C16', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C17', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C18', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C19', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C20', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C21', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C22', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C23', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C24', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C25', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C26', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C27', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C28', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C29', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C30', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C31', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C32', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C33', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C34', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C35', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('C36', 1);

# Section D
INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('D1', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('D2', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('D3', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('D4', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('D5', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('D6', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('D7', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('D8', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('D9', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('D10', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('D11', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('D12', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('D13', 1);

INSERT INTO PARKING_SLOT (NUMBER, PARKING_LOT_ID) VALUES ('D14', 1);

#####
# inserts for LANGUAGE table
#####

INSERT INTO LANGUAGE (LANGUAGE) VALUES ('English');

INSERT INTO LANGUAGE (LANGUAGE) VALUES ('Spanish');

INSERT INTO LANGUAGE (LANGUAGE) VALUES ('Portuguese');

#####
# TEST inserts for RESERVATION table
#####
INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-14', '2012-8-22', 15, 1);

INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-20', '2012-8-24', 16, 3);

INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-5', '2012-8-25', 32, 5);

INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-7', '2012-8-30', 28, 6);

INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-12', '2012-8-30', 29, 5);

INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-14', '2012-8-30', 30, 6);

INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-17', '2012-8-30', 85, 5);

INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-17', '2012-8-30', 86, 6);

INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-24', '2012-8-30', 87, 5);

INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-25', '2012-8-30', 88, 6);

INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-24', '2012-8-31', 90, 5);

INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-24', '2012-8-30', 91, 6);

INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-5', '2012-8-30', 41, 5);

INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-4', '2012-8-30', 42, 6);

INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-18', '2012-8-30', 43, 5);

INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-21', '2012-8-30', 44, 6);

INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-25', '2012-8-30', 45, 5);

INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-30', '2012-8-31', 46, 6);

INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-29', '2012-8-29', 47, 5);

INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-18', '2012-8-20', 48, 6);

INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-21', '2012-9-2', 49, 5);

INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-30', '2012-9-5', 50, 5);

INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-15', '2012-8-21', 52, 6);

INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-13', '2012-8-28', 53, 5);

INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-25', '2012-9-10', 54, 6);

INSERT INTO RESERVATION (BEGIN_DATE, END_DATE, PARKING_SLOT_ID, VEHICLE_ID) VALUES ('2012-8-21', '2012-9-5', 55, 5);
